apiVersion: v1
kind: ConfigMap
metadata:
 name: medilab-configmap-be-ns
 labels:
   storage: medilab-configmap
 namespace: dev-applications
 
data:
  #MYSQL_DATABASE_NAME: "medilab-preclinic-monolith"
  MYSQL_DATABASE_NAME: medilab-monolith-app-db
  MYSQL_DB_PORT: "3306"
  MEDILAB_DB_TYPE: "mysql"
  MEDILAB_DB_APP_SERVICE_NAME: medilab-monolith-app-db-service.dev-database
  #MEDILAB_DB_APP_SERVICE_NAME: medilab-monolith-app-db-service