apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: dev-database
spec:
  capacity: 
   storage: 2Gi      
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /var/lib/mysql   
 
